In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.8.0


In [11]:
hello = tf.constant("Hello")

In [12]:
world = tf.constant("Worlds")

In [13]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [15]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [16]:
print(result)

b'HelloWorlds'


In [17]:
a = tf.constant(10)

In [19]:
b = tf.constant(20)

In [20]:
print(a+b) # doesnt execute becuase its not inside the run()

Tensor("add_1:0", shape=(), dtype=int32)


In [23]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [24]:
result

30

In [26]:
const = tf.constant(10)

In [29]:
fill_mat = tf.fill((4,4),10)

In [30]:
fill_mat

<tf.Tensor 'Fill_1:0' shape=(4, 4) dtype=int32>

In [32]:
myzeros = tf.zeros((4,4))

In [33]:
myones = tf.ones((4,4))

In [34]:
myrandn = tf.random_normal((4,4),mean=0, stddev=1.0)

In [35]:
myrandu = tf.random_uniform((4,4), minval=1, maxval=1)

In [36]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [37]:
sess = tf.InteractiveSession()

In [39]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.1905873  -0.1263485  -0.0363555   0.25159827]
 [-0.88775074  0.98057985  0.84229577  1.2341733 ]
 [-0.97853315  2.4607835   0.4228373  -2.1964412 ]
 [-0.6280928  -0.6796644   0.4518172   0.21523994]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]




In [40]:
a = tf.constant([[1,2],
                [3,4]])

In [41]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [43]:
b = tf.constant([[10],[100]])

In [44]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [45]:
result = tf.matmul(a,b)

In [46]:
sess.run(result)

array([[210],
       [430]], dtype=int32)